use_frameworks!

platform :ios, '9.0'

target 'Monstera_Example' do
  pod 'Monstera', :path => '../'

  target 'Monstera_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
